// Generated from the Rust commands. Do not edit by hand.
// Regenerate: UPDATE_BINDINGS=1 cargo test -p night-maze-launcher
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  What the window should show now. Reads local state only. */
	snapshot: () => __TAURI_INVOKE<Snapshot>("snapshot"),
	/**  Ask the release feed for the newest version. */
	checkForUpdates: () => __TAURI_INVOKE<Snapshot>("check_for_updates"),
	/**  Download and install the version the last check found. */
	installUpdate: () => __TAURI_INVOKE<Snapshot>("install_update"),
	/**  Start the installed version. Answers as soon as the game process exists. */
	launchGame: () => __TAURI_INVOKE<Snapshot>("launch_game"),
	/**  Turn the update check on start on or off. */
	setCheckOnStart: (enabled: boolean) => __TAURI_INVOKE<Snapshot>("set_check_on_start", { enabled }),
	/**  Remove one of the launcher's own notices. */
	dismissNotice: (id: string) => __TAURI_INVOKE<Snapshot>("dismiss_notice", { id }),
	/**
	 *  Show a launcher folder in the file manager of the system.
	 * 
	 *  The page names one of two folders and never passes a path, so this cannot
	 *  be used to open anything else.
	 */
	openFolder: (folder: Folder) => __TAURI_INVOKE<null>("open_folder", { folder }),
};

/** Events */
export const events = {
	installProgress: makeEvent<InstallProgress>("install-progress"),
	snapshotChanged: makeEvent<SnapshotChanged>("snapshot-changed"),
};

/* Types */
/**  What the launcher is doing right now. */
export type Activity = 
/**  Nothing. */
{ kind: "idle" } | 
/**  A version is being downloaded or unpacked. */
{ kind: "installing"; 
/**  The version being installed. */
version: string } | 
/**  The game is running. */
{ kind: "running"; 
/**  The version that is running. */
version: string; 
/**  The process id of the game, 0 when the system did not report one. */
pid: number };

/**  A folder the page may ask to see in the file manager. */
export type Folder = 
/**  The install root. */
"install" | 
/**  The folder with the game log. */
"logs";

/**  Sent while a version is being downloaded and installed. */
export type InstallProgress = Progress;

/**  A notice the launcher wrote itself. It stays until the player dismisses it. */
export type LocalNotice = {
	/**  Unique within the state file. */
	id: string,
	/**  Why it was written. */
	kind: NoticeKind,
	/**  The version that did not start. */
	failed: string,
	/**  The version the launcher went back to, for [`NoticeKind::RolledBack`]. */
	restored?: string | null,
	/**  The last error line of the game log, when there was one. */
	detail?: string | null,
};

/**  `news.json`: the text the window shows. */
export type NewsFeed = {
	/**  Format number, see [`SCHEMA`]. */
	schema: number,
	/**  Release notes, newest first. */
	updates?: ReleaseNotes[],
	/**  Posts that are not tied to a version. */
	news?: NewsPost[],
	/**  Notices from the author, for example about a pulled release. */
	notices?: RemoteNotice[],
};

/**  A post in the News tab. */
export type NewsPost = {
	/**  Date of the post, `YYYY-MM-DD`. */
	date?: string,
	/**  The headline. */
	title?: string,
	/**  The text. */
	body?: string,
};

/**  One titled list of bullet points in the notes of a release. */
export type NotesGroup = {
	/**  The group heading. */
	title?: string,
	/**  The bullet points. */
	items?: string[],
};

/**  Why a local notice was written. */
export type NoticeKind = 
/**  A new version did not start and the previous one was restored. */
"rolled_back" | 
/**  A version did not start and there was nothing to go back to. */
"start_failed";

/**  The step an install is in. */
export type Phase = 
/**  Bytes are arriving. */
"downloading" | 
/**  The length and the checksum are compared with the manifest. */
"verifying" | 
/**  The archive is unpacked and moved into place. */
"installing";

/**  One progress report of an install. */
export type Progress = {
	/**  The version being installed. */
	version: string,
	/**  The current step. */
	phase: Phase,
	/**  Bytes received so far. */
	received: number | null,
	/**  Bytes the manifest announces. */
	total: number | null,
};

/**  The notes of one release. */
export type ReleaseNotes = {
	/**  The version the notes describe. */
	version: string,
	/**  Release date, `YYYY-MM-DD`. */
	date?: string,
	/**  A short label such as "Milestone release". */
	tag?: string,
	/**  The headline. */
	title?: string,
	/**  One intro sentence. */
	summary?: string,
	/**  Whether this entry fills the highlight card. */
	highlight?: boolean,
	/**  Groups of bullet points. */
	groups?: NotesGroup[],
};

/**  What the last update check found. */
export type Remote = 
/**  No check has finished yet. */
{ kind: "unknown" } | 
/**  The check failed. The installed version still starts. */
{ kind: "offline"; 
/**  Why, in one sentence. */
reason: string } | 
/**  The installed version is the one the manifest names. */
{ kind: "up_to_date" } | 
/**  Another version is waiting to be installed. */
{ kind: "update_available"; 
/**  The version the manifest names. */
version: string; 
/**  The size of its download in bytes. */
size: number | null } | 
/**  The release needs a newer launcher than this one. */
{ kind: "launcher_too_old"; 
/**  The lowest launcher version the manifest accepts. */
required: string };

/**  A notice from the feed. */
export type RemoteNotice = {
	/**  A stable id. */
	id?: string,
	/**  `info` or `warning`. */
	level?: string,
	/**  The headline. */
	title?: string,
	/**  The text. */
	body?: string,
};

/**  Everything the window shows, at one moment. */
export type Snapshot = {
	/**  The version of this launcher. */
	launcher_version: string,
	/**  The install root. */
	install_root: string,
	/**  The folder with the game log. */
	logs_dir: string,
	/**  The game log itself. */
	log_file: string,
	/**  The installed version Launch starts, if any. */
	current: string | null,
	/**  The version kept for rollback, if any. */
	previous: string | null,
	/**  Whether the launcher checks for updates when it opens. */
	check_on_start: boolean,
	/**  The result of the last update check. */
	remote: Remote,
	/**  What the launcher is doing. */
	activity: Activity,
	/**  One line about the newest release, from the manifest. */
	notes: string | null,
	/**  The notes feed: fresh, or the copy kept from the last successful read. */
	feed: NewsFeed | null,
	/**  Notices the launcher wrote itself. */
	notices: LocalNotice[],
};

/**
 *  Sent when the launcher changed without a command asking for it: the game
 *  exited, or a failed start made the launcher go back one version.
 */
export type SnapshotChanged = Snapshot;

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

